### ISSUE TITLE
关于其他小语种的聊天模型训练

### ISSUE THREAD

**Issue by guijuzhejiang** [920232796/bert_seq2seq#12]
感谢分享，看介绍没有提到NLG聊天任务。想请教这套代码能训练聊天任务模型吗？怎么用呢？

**Comment by 920232796** [comment]
没问题呀 跟对联 写诗 是一样的 都是序列到序列。你对照对联的代码  处理好输入输出直接就可以跑了。

**Comment by guijuzhejiang** [comment]
谢谢，我这边要训练一个小语种的对话机器人，字典vocab文件不同，就不能用预训练模型了，要自己从头训练了是吗？
另外，对联的代码也是用的UniLM策略训练的吗？

**Comment by 920232796** [comment]
1. 是的 2. 对

**Comment by 920232796** [comment]
从头训练可能有点难  感觉如果语料不是很丰富的话 会有点难训练。

**Comment by guijuzhejiang** [comment]
谢谢，两块股东1080TI，训练走起
