### ISSUE TITLE
关于target_ids 

### ISSUE THREAD

**Issue by 489597448** [920232796/bert_seq2seq#16]
在seq2seq模型中，我不明白为什么token_ids 去掉首字符 即CLS后，就是target_ids。例如在古诗词任务中，token_ids是 cls+标题+sep + 诗词 + sep，我理解targe_ids应该是  诗词，为什么代码中是 标题+sep+诗词+sep

**Comment by 920232796** [comment]
因为unilm的话 预测的时候就是通过前面的字 往后预测 一个一个预测 因此就需要模型有这种向后输出的能力。

**Comment by 489597448** [comment]
那如果我的输入中包含多段话 比如在QG问题中，输入就会变成  cls + passage  + sep + answer + sep + question ，目的是生成那个question  它会影响最后的解码吗(因为我看到你解码阶段是以sep作为终止符号的)

**Comment by 920232796** [comment]
不会影响吧，因为你把问题放在最后了，他是从倒数第二个sep开始预测的吧，然后预测到最后sep为止，没任何影响的。

**Comment by 489597448** [comment]
好的  Thank you
