### ISSUE TITLE
Question about THUCNews自动摘要

### ISSUE THREAD

**Issue by PipiZong** [920232796/bert_seq2seq#26]
Hi,

您好， 您这个例子里似乎没有一个criteria 去选出最好的model,  而只是保存了最后一个epoch下的model？

**Comment by 920232796** [comment]
对，我提供的基本都是最简单的demo，很多都没具体的测试数据测试指标，不过这个代码也好写阿，很灵活的，随便加在什么位置都可以，你可以自己加一下。

**Comment by PipiZong** [comment]
对， 谢谢啦！
