### ISSUE TITLE
NEZHA 模型 长度超过512 报错！

### ISSUE THREAD

**Issue by jinxiang-unique** [920232796/bert_seq2seq#44]
![image](https://user-images.githubusercontent.com/59439162/137344988-2db4a2e7-726c-4ef4-b708-cefe4947d61f.png)
您好，请问我在使用nezha这个预训练模型做文本摘要时，为什么长度超过512，会报错呢？还是您的内部没有相应的相对位置编码实现呢？

**Comment by 920232796** [comment]
![image](https://user-images.githubusercontent.com/32668889/137350524-dbc36487-1ead-4b49-b988-0d738c6a6663.png)
我这里目前改成了1024。

**Comment by jinxiang-unique** [comment]
请问我调用的时候该怎么设置max_len呢

**Comment by 920232796** [comment]
对 就是设置这个。

**Comment by 920232796** [comment]
这个在计算相对位置编码的时候 也会用到，所以以前默认是512 会报错。
